### ISSUE TITLE
[BUG] target.hasOwnProperty is not a function when using toml

### ISSUE THREAD

**Issue by Nabrok** [lorenwest/node-config#911]
**Describe the bug**

When reading a property of an object from the config with toml a target.hasOwnProperty is not a function error occurs.

config/default.toml:
```toml
[foo]
bar = "value"
```

test.js:
```js
const config = require("config");

console.log(config.has("foo.bar"));
console.log(config.get("foo.bar"));
```

output:
```
true
/home/test/node_modules/config/lib/util.js:191
              if (target.hasOwnProperty(property) || (property in target && typeof target[property] !== 'function')) {
                         ^

TypeError: target.hasOwnProperty is not a function
    at Object.get (/home/test/node_modules/config/lib/util.js:191:26)
    at Util.getPath (/home/test/node_modules/config/lib/util.js:606:25)
    at ConfigClass.get (/home/test/node_modules/config/lib/config.js:101:24)
    at Object.<anonymous> (/home/test/test.js:4:20)
    at Module._compile (node:internal/modules/cjs/loader:1761:14)
    at Object..js (node:internal/modules/cjs/loader:1893:10)
    at Module.load (node:internal/modules/cjs/loader:1481:32)
    at Module._load (node:internal/modules/cjs/loader:1300:12)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)

Node.js v24.13.0
```

**Expected behavior**
The property should be read.

### Please tell us about your environment:

 -  node-config version: 4.4.1
 -  node-version: 24.13.0
 - toml version: 4.1.1
 
### Other information

Works with config v4.3.0 and stops working with v4.4.0

**Comment by Nabrok** [comment]
It seems that toml removes prototypes from objects and has for some time.  I'm not sure why this would suddenly start causing a problem with 4.4 and not before.

The following change allows it to work, but I'm not sure if there are any other repercussions.

```
              if ((target.hasOwnProperty && target.hasOwnProperty(property)) || (property in target && typeof target[property] !== 'function')) {
```

**Comment by jdmarshall** [comment]
The old version of the code contained a TODO that needed to be resolved in order to finish the withModuleDefaults functionality:

```
              // Config's own defined prototype properties and methods (e.g., `get`, `has`, etc.)
              const ownProps = [
              ...Object.getOwnPropertyNames(ConfigClass.prototype), //TODO: This keeps us from moving this function to util.js where it belongs
                ...Object.getOwnPropertyNames(target),
              ]

              // Bypass proxy receiver for properties directly on the target (e.g., RegExp.prototype.source)
              // or properties that are not functions to prevent errors related to internal object methods.
              if (ownProps.includes(property) || (property in target && typeof target[property] !== 'function')) {
                return Reflect.get(target, property);
              }
```

versus the faster:

```
              if (target.hasOwnProperty(property) || (property in target && typeof target[property] !== 'function')) {
                return Reflect.get(target, property);
              }
```

But this is where it broke for toml:

```
                ...Object.getOwnPropertyNames(target), // resolved to empty list
```

And it seems like our unit tests are anemic there since this didn't result in a red test.

Other thoughts on this block of code: 

- The || clause is for very old versions of nodejs and can probably go.
- capturing the function check to the left half of the conditional is probably wrong


Do you have a repro case for this? Because it feels like you may be making a nested call on a missing parameter and getting a different error than what you used to. But I'd like to be sure I'm characterizing the issue properly. Especially if this is going to undo performance gains that were introduced in 4.4

**Comment by jdmarshall** [comment]
So it looks like node-config expects toml 2.x and it is in fact incompatible with 4.1.  Let me see if I can figure out how far we can upgrade without busting things.

**Comment by jdmarshall** [comment]
@Nabrok can you file a bug report against TOML for the fact that the objects they return do not have prototype Object? That's why this is breaking. I have a workaround that should not result in a performance regression but that's... They're wrong. That's broken, bad developer no cookie.

**Comment by Nabrok** [comment]
This seems to come from this PR: https://github.com/BinaryMuse/toml-node/pull/54 which was to allow using "constructor" as a key.

**Comment by jdmarshall** [comment]
@Nabrok 4.4.2 is live, please let us know if you still have issues.
